# .deepsource.toml

version = 1

# Optional: Paths to exclude from analysis
exclude_patterns = [
  "node_modules/**",
  "dist/**",
  "build/**",
  "target/**",           # Rust build output
  "**/*.min.js",
  "vendor/**",
  ".git/**"
]

# Optional: Identify test files and directories
test_patterns = [
  "tests/**",
  "**/__tests__/**",
  "**/*.spec.ts",
  "**/*.test.ts",
  "**/*.test.js",
  "**/*.spec.js"
]

# Enable Rust analyzer
[[analyzers]]
name = "rust"
enabled = true

# Enable JavaScript analyzer (covers JavaScript + TypeScript)
[[analyzers]]
name = "javascript"
enabled = true
dependency_file_paths = [
  "package.json",
  "yarn.lock",
  "pnpm-lock.yaml"
]

# Enable Shell analyzer
[[analyzers]]
name = "shell"
enabled = true

# Transformers (auto-formatters)
[[transformers]]
name = "rustfmt"
enabled = true

[[transformers]]
name = "prettier"
enabled = true
